spring.application.name=demo
# LINE Botの設定
line.bot.channel-token=/RuwXPCHkmjeXa8hPiYNheVup0JwH21iL5JRMWRMRp3L7r0dKe98COeBuf39281u6WDvO0Lx/9X3/ACRTRP8RThLa8bFViY2xxQh7XIhxKZ/1s/r+fvWxTX+YX0KPigFxvd3THUhmFwIf0Q0tBUh5AdB04t89/1O/w1cDnyilFU=
line.bot.user-id=Udcb0a91f916903fc9454933532865f54